//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MookEditor.Resources.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18n() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MookEditor.Resources.I18n.I18n", typeof(I18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 界面 的本地化字符串。
        /// </summary>
        public static string _interface {
            get {
                return ResourceManager.GetString("interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成就 的本地化字符串。
        /// </summary>
        public static string achievements {
            get {
                return ResourceManager.GetString("achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警示 的本地化字符串。
        /// </summary>
        public static string alerts {
            get {
                return ResourceManager.GetString("alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自治 的本地化字符串。
        /// </summary>
        public static string autonomy {
            get {
                return ResourceManager.GetString("autonomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剧本 的本地化字符串。
        /// </summary>
        public static string bookmarks {
            get {
                return ResourceManager.GetString("bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建筑 的本地化字符串。
        /// </summary>
        public static string buildings {
            get {
                return ResourceManager.GetString("buildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否关闭程序？ 的本地化字符串。
        /// </summary>
        public static string CloseProgram {
            get {
                return ResourceManager.GetString("CloseProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭项目 的本地化字符串。
        /// </summary>
        public static string CloseProject {
            get {
                return ResourceManager.GetString("CloseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码编辑器 的本地化字符串。
        /// </summary>
        public static string CodeEditor {
            get {
                return ResourceManager.GetString("CodeEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码格式化成功 的本地化字符串。
        /// </summary>
        public static string CodeFormatSuccessful {
            get {
                return ResourceManager.GetString("CodeFormatSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公共 的本地化字符串。
        /// </summary>
        public static string common {
            get {
                return ResourceManager.GetString("common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国家 的本地化字符串。
        /// </summary>
        public static string countries {
            get {
                return ResourceManager.GetString("countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建模组 的本地化字符串。
        /// </summary>
        public static string CreateModule {
            get {
                return ResourceManager.GetString("CreateModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光标 的本地化字符串。
        /// </summary>
        public static string cursors {
            get {
                return ResourceManager.GetString("cursors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪切 的本地化字符串。
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 决议 的本地化字符串。
        /// </summary>
        public static string decisions {
            get {
                return ResourceManager.GetString("decisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定义 的本地化字符串。
        /// </summary>
        public static string defines {
            get {
                return ResourceManager.GetString("defines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目录 的本地化字符串。
        /// </summary>
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件图片 的本地化字符串。
        /// </summary>
        public static string event_pictures {
            get {
                return ResourceManager.GetString("event_pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件 的本地化字符串。
        /// </summary>
        public static string events {
            get {
                return ResourceManager.GetString("events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标志 的本地化字符串。
        /// </summary>
        public static string flags {
            get {
                return ResourceManager.GetString("flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体 的本地化字符串。
        /// </summary>
        public static string fonts {
            get {
                return ResourceManager.GetString("fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏规则 的本地化字符串。
        /// </summary>
        public static string game_rules {
            get {
                return ResourceManager.GetString("game_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 的本地化字符串。
        /// </summary>
        public static string gfx {
            get {
                return ResourceManager.GetString("gfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 历史 的本地化字符串。
        /// </summary>
        public static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国家精神 的本地化字符串。
        /// </summary>
        public static string ideas {
            get {
                return ResourceManager.GetString("ideas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意识形态 的本地化字符串。
        /// </summary>
        public static string ideologies {
            get {
                return ResourceManager.GetString("ideologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动资源 的本地化字符串。
        /// </summary>
        public static string launcher_assets {
            get {
                return ResourceManager.GetString("launcher-assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将领 的本地化字符串。
        /// </summary>
        public static string leaders {
            get {
                return ResourceManager.GetString("leaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行 的本地化字符串。
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地化 的本地化字符串。
        /// </summary>
        public static string localisation {
            get {
                return ResourceManager.GetString("localisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图 的本地化字符串。
        /// </summary>
        public static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中号 的本地化字符串。
        /// </summary>
        public static string medium {
            get {
                return ResourceManager.GetString("medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少括号 的本地化字符串。
        /// </summary>
        public static string MissingBraces {
            get {
                return ResourceManager.GetString("MissingBraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组设置 的本地化字符串。
        /// </summary>
        public static string ModSetting {
            get {
                return ResourceManager.GetString("ModSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组编辑器 的本地化字符串。
        /// </summary>
        public static string MookEditor {
            get {
                return ResourceManager.GetString("MookEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音乐 的本地化字符串。
        /// </summary>
        public static string music {
            get {
                return ResourceManager.GetString("music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名字 的本地化字符串。
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国家焦点 的本地化字符串。
        /// </summary>
        public static string national_focus {
            get {
                return ResourceManager.GetString("national_focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建文件 的本地化字符串。
        /// </summary>
        public static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建文件夹 的本地化字符串。
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建模组 的本地化字符串。
        /// </summary>
        public static string NewModule {
            get {
                return ResourceManager.GetString("NewModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件 的本地化字符串。
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件夹 的本地化字符串。
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开模组 的本地化字符串。
        /// </summary>
        public static string OpenMod {
            get {
                return ResourceManager.GetString("OpenMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴 的本地化字符串。
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 肖像 的本地化字符串。
        /// </summary>
        public static string portraits {
            get {
                return ResourceManager.GetString("portraits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名 的本地化字符串。
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存为 的本地化字符串。
        /// </summary>
        public static string Saveas {
            get {
                return ResourceManager.GetString("Saveas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小号 的本地化字符串。
        /// </summary>
        public static string small {
            get {
                return ResourceManager.GetString("small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音效 的本地化字符串。
        /// </summary>
        public static string sound {
            get {
                return ResourceManager.GetString("sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电影配乐 的本地化字符串。
        /// </summary>
        public static string soundtrack {
            get {
                return ResourceManager.GetString("soundtrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 省份 的本地化字符串。
        /// </summary>
        public static string states {
            get {
                return ResourceManager.GetString("states", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 科技 的本地化字符串。
        /// </summary>
        public static string technologies {
            get {
                return ResourceManager.GetString("technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地形 的本地化字符串。
        /// </summary>
        public static string terrain {
            get {
                return ResourceManager.GetString("terrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 教程 的本地化字符串。
        /// </summary>
        public static string tutorial {
            get {
                return ResourceManager.GetString("tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位 的本地化字符串。
        /// </summary>
        public static string units {
            get {
                return ResourceManager.GetString("units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
